### ISSUE TITLE
Filter disabled or expired posts

### ISSUE THREAD

**Issue by vincemoley** [dmashuda/ja-next-step#21]
Prevent Disabled and expired posts from displaying unless in admin mode

**Comment by vincemoley** [comment]
Partially implemented, but can't figure out how to populate the post start_date & end_date @dmashuda

**Comment by dmashuda** [comment]
`+    activeWhere = Post.where(:active => true, :start_date => 20000.year.ago..Date.today, :end_date => Date.today..20000.year.from_now)
`

it may not be the most correct (cannot see posts 20000 years from now) but it is the only way that I know how to create that query without inlining sql

**Comment by vincemoley** [comment]
This does not completely solve the problem b/c start and end date are not required and can be null
